### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by AJEvans3** [pepa-linha/Adminer-Design-Dark#12]
I am having difficulties in stalling the theme. I have Adminer installed on Unraid. How do I go about installing the theme in this manner. Please see attached screenshot.
![Screenshot 2021-08-11 200517](https://user-images.githubusercontent.com/56004016/129132225-ed0e99da-f6c7-4390-93f7-7c74e1a29f5c.png)

**Comment by pepa-linha** [comment]
Um, I am sorry I don't know Unraid.

Any other theme works?
