### ISSUE TITLE
Quick fix for windows and linux. The dropdowns were white on white.

### ISSUE THREAD

**Issue by barnacker** [pepa-linha/Adminer-Design-Dark#3]
I fixed it on my server by adding this code at the line below:
```
option {
    background: #312f42;
}
```
https://github.com/pepa-linha/Adminer-Design-Dark/blob/d43a039cd30a163494b38706af18579896fe012f/adminer.css#L628

**Comment by pepa-linha** [comment]
Thanks, it should be fixed by darker color for option text.
